DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	firstName varchar(128),
	lastName varchar(128),
	department BIGINT,
	FOREIGN KEY (department) REFERENCES department(id)
);